name: CI

on: 
  push:
  schedule:
    - cron: '0 9 15 * *'

jobs:
  build-logos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          repository: Randomblock1/FleetsBGone
          submodules: true

      - name: Prepare Theos
        uses: randomblock1/theos-action@main

      - name: Build package
        run: |
          rm -f packages/*
          make package FINALPACKAGE=1

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: "Package built by ${{ matrix.os }}"
          path: ${{ github.workspace }}/packages/*.deb

  # TODO: Add a job to build an Orion tweak
